# Generated by Django 4.2.14 on 2024-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcurementApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
