# Generated by Django 4.2.14 on 2024-07-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcurementApp', '0006_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
