# Generated by Django 4.2.14 on 2024-07-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcurementApp', '0007_supplier_terms_accepted_alter_supplier_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
